config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :citations do
    resources :comments
  end

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/citation.rb
class Citation < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :nick, presence: true,
                    length: { minimum: 3 }

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :citation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/citations_controller.rb
class CitationsController < ApplicationController

  def index
      @citations = Citation.all
  end

  def show
    @citation = Citation.find(params[:id])
  end

  def new
    @citation = Citation.new
  end

  def edit
    @citation = Citation.find(params[:id])
  end

  def create
    @citation = Citation.new(citation_params)

    if @citation.save
      redirect_to @citation
    else
      render 'new'
    end
  end

  def update
    @citation = Citation.find(params[:id])

    if @citation.update(citation_params)
      redirect_to @citation
    else
      render 'edit'
    end
  end

  def destroy
    @citation = Citation.find(params[:id])
    @citation.destroy

    redirect_to citations_path
  end

  private
  def citation_params
    params.require(:citation).permit(:nick, :text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @citation = Citation.find(params[:citation_id])
    @comment = @citation.comments.create(comment_params)
    redirect_to citation_path(@citation)
  end

  def destroy
    @citation = Citation.find(params[:citation_id])
    @comment = @citation.comments.find(params[:id])
    @comment.destroy
    redirect_to citation_path(@citation)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/citations_helper.rb
module CitationsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/citations/_form.html.erb
<h1>New Citation</h1>
<%= form_with scope: :citation, url: citations_path, local: true do |form| %>

<% if @citation.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@citation.errors.count, "error") %> prohibited
      this citation from being saved:
    </h2>
    <ul>
      <% @citation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <p>
    <%= form.label :author %><br>
    <%= form.text_field :nick %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/citations/edit.html.erb
<h1>Edit Citation</h1>
<%= form_with scope: :citation, url: citations_path, local: true do |form| %>

<% if @citation.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@citation.errors.count, "error") %> prohibited
      this citation from being saved:
    </h2>
    <ul>
      <% @citation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <p>
    <%= form.label :author %><br>
    <%= form.text_field :nick %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>


<%= link_to 'Back', citations_path %>

app/views/citations/index.html.erb
<h1>List of quotations</h1>
<%= link_to 'New citation', new_citation_path %>
<table>
  <tr>
    <th>Author</th>
    <th>Text</th>
    <th></th>
  </tr>

  <% @citations.each do |citation| %>
    <tr>
      <td><%= citation.nick %></td>
      <td><%= citation.text %></td>
      <td><%= link_to 'Show', citation_path(citation) %></td>
      <td><%= link_to 'Edit', edit_citation_path(citation) %></td>
      <td><%= link_to 'Delete', citation_path(citation),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/citations/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', citations_path %>

app/views/citations/show.html.erb
<p>
  <strong>Author:</strong>
  <%= @citation.nick %>
</p>

<p>
  <strong>Text:</strong>
  <%= @citation.text %>
</p>

<h2>Comments</h2>
<%= render @citation.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Back', citations_path %>
<%= link_to 'Edit', edit_citation_path(@citation) %> |

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.citation, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @citation, @citation.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Netguru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<body>
<h1>Hello on my website</h1>
<p>Click below if you want to see quotes!</p>
<%= link_to 'Citation', controller: 'citations' %>
</body>